classdef QuadLoadPlant2D2I < HybridDrakeSystem
  properties
    
    e = 0.3;  % coefficient of restitution
    l = 1;
    mq = 4;
    ml = 1;
    g = 9.81;
    I1 = 2;
    d = 0.25;
    vtrigg = 0.3;
  end
  
  methods
    function obj = QuadLoadPlant2D2I()
      obj = obj@HybridDrakeSystem(...
        2, ...  % number of inputs
        13);     % number of outputs
      obj=obj.setInputLimits(100*[-1;-1],100*[1;1]);
      
      % create flight mode system
      sys = QuadLoadAsOnePhasePlant2D2I();
      obj = setInputFrame(obj,sys.getInputFrame);
      obj = setOutputFrame(obj,sys.getOutputFrame);
      
      sys2 = QuadLoadFlightPhasePlant2D2I();
      sys2 = setInputFrame(sys2,sys.getInputFrame);
      sys2 = setOutputFrame(sys2,sys.getOutputFrame);
      
      
      [obj,asone_mode] = addMode(obj,sys);  % add the 1st mode
      [obj,flight_mode] = addMode(obj,sys2);  % add the 2nd mode
      %obj = obj.setInputLimits(-300,300);
      obj = addTransition(obj, ...
        asone_mode, ...            % from mode
        @ForceGuard1, ...                    % q-r<=0 & qdot<=0 %andGuards(obj,g1,g2)
        @collisionDynamics12, ...    % transition method
        true, ...                 % not direct feedthrough %IMPORTANT
        true,flight_mode);%,...                   % time invariant
        %flight_mode);              % to mode 5%%%HUGE _ AVOID ERROR IN HyTO
      obj = addTransition(obj, ...
        flight_mode, ...            % from mode
        andGuards(obj,@LengthGuard,@IncrLengthGuard,@LowSpeed), ...                    % q-r<=0 & qdot<=0 %andGuards(obj,g1,g2)
        @collisionDynamics21, ...    % transition method
        false, ...                 % not direct feedthrough %IMPORTANT
        true,asone_mode);%,...                   % time invariant
        %asone_mode);              % to mode 
      obj = addTransition(obj, ...
        flight_mode, ...            % from mode
        andGuards(obj,@LengthGuard,@IncrLengthGuard,@HighSpeed), ...                    % q-r<=0 & qdot<=0 %andGuards(obj,g1,g2)
        @collisionDynamics22, ...    % transition method
        false, ...                 % not direct feedthrough %IMPORTANT
        true,...                   % time invariant
        flight_mode);              % to mode 
    obj = setSimulinkParam(obj,'InitialStep','1e-3','MaxStep','0.05');
    end

    
    function [g,dg] = ForceGuard1(obj,t,x,u)
      u1=u(1);u2=u(2);
      m=obj.mq;l=obj.l;
      al=x(6);dal=x(12);th=x(3);
        
      g = m*(l)^2*(dal)^2+cos(al-th)*(u1+u2);%  CONSIDER +EPS % CONSIDER g1.5=distance 
      g = g + eps;
      dg = [ 0, 0, 0, sin(al - th)*(u1 + u2), 0, 0, -sin(al - th)*(u1 + u2), 0, 0, 0, 0, 0, 2*dal*l^2*m, cos(al - th), cos(al - th)];
    end
    function [g,dg] = LengthGuard(obj,t,xv,u)
        x=xv(1);y=xv(2);x2=xv(4);y2=xv(5);
      g = obj.l-sqrt((x-x2)^2+(y-y2)^2);
      g = g + eps;
      dh22dx=[ -(x - x2)/((x - x2)^2 + (y - y2)^2)^(1/2), -(y - y2)/((x - x2)^2 + (y - y2)^2)^(1/2), 0, (x - x2)/((x - x2)^2 + (y - y2)^2)^(1/2), (y - y2)/((x - x2)^2 + (y - y2)^2)^(1/2), 0, 0, 0, 0, 0, 0, 0];
      dg = [0,dh22dx,0,0];
    end
    function [g,dg] = IncrLengthGuard(obj,t,xv,u)
        x=xv(1);y=xv(2);x2=xv(4);y2=xv(5);dx=xv(7);dy=xv(8);dx2=xv(10);dy2=xv(11);
        
      g = -((x-x2)*(dx-dx2)+(y-y2)*(dy-dy2));   % theta_st >= 0
      g = g + eps;
      dkdh22dx=[dx2 - dx, dy2 - dy, 0, dx - dx2, dy - dy2, 0, x2 - x, y2 - y, 0, x - x2, y - y2, 0];
      dg = [0,dkdh22dx,0,0];
    end

    function [g,dg] = LowSpeed(obj,t,xv,u)
        x=xv(1);y=xv(2);x2=xv(4);y2=xv(5);dx=xv(7);dy=xv(8);dx2=xv(10);dy2=xv(11);
      g = ((x-x2)*(dx-dx2)+(y-y2)*(dy-dy2))-obj.vtrigg+eps;   % theta_st >= 0
      dkdh22dx=-[dx2 - dx, dy2 - dy, 0, dx - dx2, dy - dy2, 0, x2 - x, y2 - y, 0, x - x2, y - y2, 0];
      dg = [0,dkdh22dx,0,0];
    end
    
    function [g,dg] = HighSpeed(obj,t,xv,u)
        x=xv(1);y=xv(2);x2=xv(4);y2=xv(5);dx=xv(7);dy=xv(8);dx2=xv(10);dy2=xv(11);
      g = -(((x-x2)*(dx-dx2)+(y-y2)*(dy-dy2))-obj.vtrigg);   % theta_st >= 0
      dkdh22dx=[dx2 - dx, dy2 - dy, 0, dx - dx2, dy - dy2, 0, x2 - x, y2 - y, 0, x - x2, y - y2, 0];
      dg = [0,dkdh22dx,0,0];
    end    
    
    
    function [xn,m,status,dxn] = collisionDynamics12(obj,m,t,x,u)%[xp,mode,status,dxp]
      l=obj.l;al=x(5);dal=x(10);
      xn = x;
      xn(4) = x(1)+l*sin(x(6));
      xn(5) = x(2)-l*cos(x(6));
      xn(6) = 0;
      xn(10) = x(7)+l*cos(x(6))*x(12);
      xn(11) = x(8)+l*sin(x(6))*x(12);
      xn(12) = 0;
      status = 0;                   
      m=2;
      dxndx =  [[ 1, 0, 0, 0, 0,              0, 0, 0, 0, 0, 0,         0]
                [ 0, 1, 0, 0, 0,              0, 0, 0, 0, 0, 0,         0]
                [ 0, 0, 1, 0, 0,              0, 0, 0, 0, 0, 0,         0]
                [ 1, 0, 0, 0, 0,      l*cos(al), 0, 0, 0, 0, 0,         0]
                [ 0, 1, 0, 0, 0,      l*sin(al), 0, 0, 0, 0, 0,         0]
                [ 0, 0, 0, 0, 0,              0, 0, 0, 0, 0, 0,         0]
                [ 0, 0, 0, 0, 0,              0, 1, 0, 0, 0, 0,         0]
                [ 0, 0, 0, 0, 0,              0, 0, 1, 0, 0, 0,         0]
                [ 0, 0, 0, 0, 0,              0, 0, 0, 1, 0, 0,         0]
                [ 0, 0, 0, 0, 0, -dal*l*sin(al), 1, 0, 0, 0, 0, l*cos(al)]
                [ 0, 0, 0, 0, 0,  dal*l*cos(al), 0, 1, 0, 0, 0, l*sin(al)]
                [ 0, 0, 0, 0, 0,              0, 0, 0, 0, 0, 0,         0]]; %8 states
      dxn = [zeros(12,2),dxndx,zeros(12,2)];
    end
    
    function [xn,m,status,dxn] = collisionDynamics21(obj,m,t,xv,u)%[xp,mode,status,dxp]
      x=xv(1);y=xv(2);th=xv(3);x2=xv(4);y2=xv(5);
      dx=xv(7);dy=xv(8);dth=xv(9);dx2=xv(10);dy2=xv(11);
      ml=obj.ml;mq=obj.mq;l=obj.l;
      aln = pi/2+atan2(y2-y,x2-x);
      xn=zeros(12,1);
        v2i=dx2*sin(aln)-dy2*cos(aln);
        v1i=dx*sin(aln)-dy*cos(aln);
        v2f=(ml*v2i+mq*v1i);
        v1f=v2f;
        v2ort=dx2*cos(aln)+dy2*sin(aln);
        v1ort=dx*cos(aln)+dy*sin(aln);
        dxn=v1ort*cos(aln)+v1f*sin(aln);
        dyn=v1ort*sin(aln)-v1f*cos(aln);   
        dx2n=v2ort*cos(aln)+v2f*sin(aln);
        dy2n=v2ort*sin(aln)-v2f*cos(aln);
      
        xn(1) = x;
        xn(2) = y;
        xn(3) = th;
        xn(4) = 0;
        xn(5) = 0;
        xn(6) = aln;
        xn(7) = dxn;
        xn(8) = dyn;
        xn(9) = dth;
        xn(10) = 0;
        xn(11) = 0;
        xn(12) = 1/l*((dx2n-dxn)*cos(aln)+(dy2n-dyn)*sin(aln));
      status = 0;
      m=1;
      dxndx = [[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                   -(y - y2)/((x - x2)^2 + (y - y2)^2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (x - x2)/((x - x2)^2 + (y - y2)^2), 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (y - y2)/((x - x2)^2 + (y - y2)^2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                   -(x - x2)/((x - x2)^2 + (y - y2)^2), 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[ ((y - y2)*(dy*x^2 + dy*x2^2 - dy*y^2 - dy*y2^2 - dy2*ml*x^2 - dy2*ml*x2^2 - dy*mq*x^2 - dy*mq*x2^2 + dy2*ml*y^2 + dy2*ml*y2^2 + dy*mq*y^2 + dy*mq*y2^2 - 2*dy*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y - 2*dx*x2*y2 + 2*dy*y*y2 + 2*dy2*ml*x*x2 + 2*dy*mq*x*x2 + 2*dx2*ml*x*y - 2*dx2*ml*x*y2 - 2*dx2*ml*x2*y + 2*dx2*ml*x2*y2 + 2*dx*mq*x*y - 2*dx*mq*x*y2 - 2*dx*mq*x2*y + 2*dx*mq*x2*y2 - 2*dy2*ml*y*y2 - 2*dy*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), -((x - x2)*(dy*x^2 + dy*x2^2 - dy*y^2 - dy*y2^2 - dy2*ml*x^2 - dy2*ml*x2^2 - dy*mq*x^2 - dy*mq*x2^2 + dy2*ml*y^2 + dy2*ml*y2^2 + dy*mq*y^2 + dy*mq*y2^2 - 2*dy*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y - 2*dx*x2*y2 + 2*dy*y*y2 + 2*dy2*ml*x*x2 + 2*dy*mq*x*x2 + 2*dx2*ml*x*y - 2*dx2*ml*x*y2 - 2*dx2*ml*x2*y + 2*dx2*ml*x2*y2 + 2*dx*mq*x*y - 2*dx*mq*x*y2 - 2*dx*mq*x2*y + 2*dx*mq*x2*y2 - 2*dy2*ml*y*y2 - 2*dy*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0, -((y - y2)*(dy*x^2 + dy*x2^2 - dy*y^2 - dy*y2^2 - dy2*ml*x^2 - dy2*ml*x2^2 - dy*mq*x^2 - dy*mq*x2^2 + dy2*ml*y^2 + dy2*ml*y2^2 + dy*mq*y^2 + dy*mq*y2^2 - 2*dy*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y - 2*dx*x2*y2 + 2*dy*y*y2 + 2*dy2*ml*x*x2 + 2*dy*mq*x*x2 + 2*dx2*ml*x*y - 2*dx2*ml*x*y2 - 2*dx2*ml*x2*y + 2*dx2*ml*x2*y2 + 2*dx*mq*x*y - 2*dx*mq*x*y2 - 2*dx*mq*x2*y + 2*dx*mq*x2*y2 - 2*dy2*ml*y*y2 - 2*dy*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), ((x - x2)*(dy*x^2 + dy*x2^2 - dy*y^2 - dy*y2^2 - dy2*ml*x^2 - dy2*ml*x2^2 - dy*mq*x^2 - dy*mq*x2^2 + dy2*ml*y^2 + dy2*ml*y2^2 + dy*mq*y^2 + dy*mq*y2^2 - 2*dy*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y - 2*dx*x2*y2 + 2*dy*y*y2 + 2*dy2*ml*x*x2 + 2*dy*mq*x*x2 + 2*dx2*ml*x*y - 2*dx2*ml*x*y2 - 2*dx2*ml*x2*y + 2*dx2*ml*x2*y2 + 2*dx*mq*x*y - 2*dx*mq*x*y2 - 2*dx*mq*x2*y + 2*dx*mq*x2*y2 - 2*dy2*ml*y*y2 - 2*dy*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,        (mq*x^2 - 2*mq*x*x2 + mq*x2^2 + y^2 - 2*y*y2 + y2^2)/abs(x - x2 + y*1i - y2*1i)^2,                               ((x - x2)*(y - y2)*(mq - 1))/abs(x - x2 + y*1i - y2*1i)^2, 0,                                            (ml*(x - x2)^2)/abs(x - x2 + y*1i - y2*1i)^2,                                      (ml*(x - x2)*(y - y2))/abs(x - x2 + y*1i - y2*1i)^2, 0]
[ ((y - y2)*(dx*x^2 + dx*x2^2 - dx*y^2 - dx*y2^2 - dx2*ml*x^2 - dx2*ml*x2^2 - dx*mq*x^2 - dx*mq*x2^2 + dx2*ml*y^2 + dx2*ml*y2^2 + dx*mq*y^2 + dx*mq*y2^2 - 2*dx*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y + 2*dy*x2*y2 + 2*dx*y*y2 + 2*dx2*ml*x*x2 + 2*dx*mq*x*x2 - 2*dy2*ml*x*y + 2*dy2*ml*x*y2 + 2*dy2*ml*x2*y - 2*dy2*ml*x2*y2 - 2*dy*mq*x*y + 2*dy*mq*x*y2 + 2*dy*mq*x2*y - 2*dy*mq*x2*y2 - 2*dx2*ml*y*y2 - 2*dx*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), -((x - x2)*(dx*x^2 + dx*x2^2 - dx*y^2 - dx*y2^2 - dx2*ml*x^2 - dx2*ml*x2^2 - dx*mq*x^2 - dx*mq*x2^2 + dx2*ml*y^2 + dx2*ml*y2^2 + dx*mq*y^2 + dx*mq*y2^2 - 2*dx*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y + 2*dy*x2*y2 + 2*dx*y*y2 + 2*dx2*ml*x*x2 + 2*dx*mq*x*x2 - 2*dy2*ml*x*y + 2*dy2*ml*x*y2 + 2*dy2*ml*x2*y - 2*dy2*ml*x2*y2 - 2*dy*mq*x*y + 2*dy*mq*x*y2 + 2*dy*mq*x2*y - 2*dy*mq*x2*y2 - 2*dx2*ml*y*y2 - 2*dx*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0, -((y - y2)*(dx*x^2 + dx*x2^2 - dx*y^2 - dx*y2^2 - dx2*ml*x^2 - dx2*ml*x2^2 - dx*mq*x^2 - dx*mq*x2^2 + dx2*ml*y^2 + dx2*ml*y2^2 + dx*mq*y^2 + dx*mq*y2^2 - 2*dx*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y + 2*dy*x2*y2 + 2*dx*y*y2 + 2*dx2*ml*x*x2 + 2*dx*mq*x*x2 - 2*dy2*ml*x*y + 2*dy2*ml*x*y2 + 2*dy2*ml*x2*y - 2*dy2*ml*x2*y2 - 2*dy*mq*x*y + 2*dy*mq*x*y2 + 2*dy*mq*x2*y - 2*dy*mq*x2*y2 - 2*dx2*ml*y*y2 - 2*dx*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), ((x - x2)*(dx*x^2 + dx*x2^2 - dx*y^2 - dx*y2^2 - dx2*ml*x^2 - dx2*ml*x2^2 - dx*mq*x^2 - dx*mq*x2^2 + dx2*ml*y^2 + dx2*ml*y2^2 + dx*mq*y^2 + dx*mq*y2^2 - 2*dx*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y + 2*dy*x2*y2 + 2*dx*y*y2 + 2*dx2*ml*x*x2 + 2*dx*mq*x*x2 - 2*dy2*ml*x*y + 2*dy2*ml*x*y2 + 2*dy2*ml*x2*y - 2*dy2*ml*x2*y2 - 2*dy*mq*x*y + 2*dy*mq*x*y2 + 2*dy*mq*x2*y - 2*dy*mq*x2*y2 - 2*dx2*ml*y*y2 - 2*dx*mq*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,                                ((x - x2)*(y - y2)*(mq - 1))/abs(x - x2 + y*1i - y2*1i)^2,       (x^2 - 2*x*x2 + x2^2 + mq*y^2 - 2*mq*y*y2 + mq*y2^2)/abs(x - x2 + y*1i - y2*1i)^2, 0,                                     (ml*(x - x2)*(y - y2))/abs(x - x2 + y*1i - y2*1i)^2,                                             (ml*(y - y2)^2)/abs(x - x2 + y*1i - y2*1i)^2, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 1,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0, 0,                                                                                        0,                                                                                       0, 0,                                                                                       0,                                                                                        0, 0]
[                                                                                                                                                                                                                                                                                                                                                                                           ((y - y2)*(dx*x - dx*x2 - dx2*x + dx2*x2 + dy*y - dy*y2 - dy2*y + dy2*y2))/(l*abs(x - x2 + y*1i - y2*1i)^3),                                                                                                                                                                                                                                                                                                                                                                                           -((x - x2)*(dx*x - dx*x2 - dx2*x + dx2*x2 + dy*y - dy*y2 - dy2*y + dy2*y2))/(l*abs(x - x2 + y*1i - y2*1i)^3), 0,                                                                                                                                                                                                                                                                                                                                                                                           -((y - y2)*(dx*x - dx*x2 - dx2*x + dx2*x2 + dy*y - dy*y2 - dy2*y + dy2*y2))/(l*abs(x - x2 + y*1i - y2*1i)^3),                                                                                                                                                                                                                                                                                                                                                                                           ((x - x2)*(dx*x - dx*x2 - dx2*x + dx2*x2 + dy*y - dy*y2 - dy2*y + dy2*y2))/(l*abs(x - x2 + y*1i - y2*1i)^3), 0, -((y - y2)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2))/(l*abs(x - x2 + y*1i - y2*1i)^3), ((x - x2)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2))/(l*abs(x - x2 + y*1i - y2*1i)^3), 0, ((y - y2)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2))/(l*abs(x - x2 + y*1i - y2*1i)^3), -((x - x2)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2))/(l*abs(x - x2 + y*1i - y2*1i)^3), 0]]; %8 states
      dxn = [zeros(12,2),dxndx,zeros(12,2)];
    end
    
    function [xn,m,status,dxn] = collisionDynamics22(obj,m,t,xv,u)
      x=xv(1);y=xv(2);th=xv(3);x2=xv(4);y2=xv(5);
      dx=xv(7);dy=xv(8);dth=xv(9);dx2=xv(10);dy2=xv(11);e=obj.e;
      ml=obj.ml;mq=obj.mq;
        aln = pi/2+atan2(y2-y,x2-x);
        v2i=dx2*sin(aln)-dy2*cos(aln);
        v1i=dx*sin(aln)-dy*cos(aln);
        v2f=((ml*v2i+mq*v1i)-mq*e*(v2i-v1i))/(mq+ml);
        v1f=v2f+e*(v2i-v1i);
        v2ort=dx2*cos(aln)+dy2*sin(aln);
        v1ort=dx*cos(aln)+dy*sin(aln);
        dx2n=v2ort*cos(aln)+v2f*sin(aln);
        dy2n=v2ort*sin(aln)-v2f*cos(aln);
        dxn=v1ort*cos(aln)+v1f*sin(aln);
        dyn=v1ort*sin(aln)-v1f*cos(aln);
        
        xn=zeros(12,1);
        xn(1) = x;
        xn(2) = y;
        xn(3) = th;
        xn(4) = x2;
        xn(5) = y2;
        xn(6) = 0;
        xn(7) = dxn;
        xn(8) = dyn;
        xn(9) = dth;
        xn(10) = dx2n;
        xn(11) = dy2n;
        xn(12) = 0;
        
      status = 0;                   %m ??????????????
      m=2;

      dxndx = [[                                                                                                                                                                                                                                                                                                                                                 1,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 1, 0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 1,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                                                                                                                                                                                                 1,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 1, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[  (ml*(y - y2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), -(ml*(x - x2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0, -(ml*(y - y2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)),  (ml*(x - x2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0, (mq*x^2 + mq*x2^2 + ml*y^2 + ml*y2^2 + mq*y^2 + mq*y2^2 - e*ml*x^2 - e*ml*x2^2 - 2*mq*x*x2 - 2*ml*y*y2 - 2*mq*y*y2 + 2*e*ml*x*x2)/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)),                                                                                                   -(ml*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0,                                                                                                           (ml*(x - x2)^2*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)),                                                                                                    (ml*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0]
[  (ml*(y - y2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), -(ml*(x - x2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0, -(ml*(y - y2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)),  (ml*(x - x2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,                                                                                                   -(ml*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), (ml*x^2 + ml*x2^2 + mq*x^2 + mq*x2^2 + mq*y^2 + mq*y2^2 - e*ml*y^2 - e*ml*y2^2 - 2*ml*x*x2 - 2*mq*x*x2 - 2*mq*y*y2 + 2*e*ml*y*y2)/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0,                                                                                                    (ml*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)),                                                                                                           (ml*(y - y2)^2*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 1,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
[ -(mq*(y - y2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)),  (mq*(x - x2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,  (mq*(y - y2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), -(mq*(x - x2)*(e + 1)*(dy*x^2 + dy*x2^2 - dy2*x^2 - dy2*x2^2 - dy*y^2 - dy*y2^2 + dy2*y^2 + dy2*y2^2 - 2*dy*x*x2 + 2*dy2*x*x2 - 2*dx*x*y + 2*dx*x*y2 + 2*dx*x2*y + 2*dx2*x*y - 2*dx*x2*y2 - 2*dx2*x*y2 - 2*dx2*x2*y + 2*dx2*x2*y2 + 2*dy*y*y2 - 2*dy2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,                                                                                                           (mq*(x - x2)^2*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)),                                                                                                    (mq*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0, (ml*x^2 + ml*x2^2 + ml*y^2 + ml*y2^2 + mq*y^2 + mq*y2^2 - e*mq*x^2 - e*mq*x2^2 - 2*ml*x*x2 - 2*ml*y*y2 - 2*mq*y*y2 + 2*e*mq*x*x2)/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)),                                                                                                   -(mq*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0]
[ -(mq*(y - y2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)),  (mq*(x - x2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,  (mq*(y - y2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), -(mq*(x - x2)*(e + 1)*(dx*x^2 + dx*x2^2 - dx2*x^2 - dx2*x2^2 - dx*y^2 - dx*y2^2 + dx2*y^2 + dx2*y2^2 - 2*dx*x*x2 + 2*dx2*x*x2 + 2*dy*x*y - 2*dy*x*y2 - 2*dy*x2*y - 2*dy2*x*y + 2*dy*x2*y2 + 2*dy2*x*y2 + 2*dy2*x2*y - 2*dy2*x2*y2 + 2*dx*y*y2 - 2*dx2*y*y2))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)*(x^2 - 2*x*x2 + x2^2 + y^2 - 2*y*y2 + y2^2)), 0,                                                                                                    (mq*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)),                                                                                                           (mq*(y - y2)^2*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0,                                                                                                   -(mq*(x - x2)*(y - y2)*(e + 1))/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), (ml*x^2 + ml*x2^2 + mq*x^2 + mq*x2^2 + ml*y^2 + ml*y2^2 - e*mq*y^2 - e*mq*y2^2 - 2*ml*x*x2 - 2*mq*x*x2 - 2*ml*y*y2 + 2*e*mq*y*y2)/(abs(x - x2 + y*1i - y2*1i)^2*(ml + mq)), 0]
[                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                 0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0,                                                                                                                                                                          0,                                                                                                                                                                          0, 0]
          
      ]; %12 states
      dxn = [zeros(12,2),dxndx,zeros(12,2)];
      
    end
    
  end  
  methods (Static=true)
    function run
      b=BnBPlant2D;
      v=BallVisualizer2D(b);
      x=b.simulate([0 5],[2; 0; 3; 0; 2.5; 0; 0; 0; 1]);
      v.playback(x);
    end
  end
end
